# Generated by Django 5.1.6 on 2025-02-25 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_domesticairports_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='from_airport',
            new_name='from_airport_name',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='to_airport',
            new_name='to_airport_name',
        ),
    ]
