# Generated by Django 5.1.6 on 2025-02-27 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_from_airport_shipment_from_airport_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingSearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='main.shipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
