# Generated by Django 5.1.6 on 2025-02-27 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_trackingsearchhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingsearchhistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
