# Generated by Django 5.1.6 on 2025-02-27 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingsearchhistory',
            name='shipment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='main.shipment'),
        ),
    ]
