# Generated by Django 5.1.6 on 2025-02-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_trackingsearchhistory_shipment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='from_airport_code',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_airport_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='from_airport_place',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_airport_code',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_airport_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='to_airport_place',
        ),
        migrations.AddField(
            model_name='shipment',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cancellation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
