# Generated by Django 5.1.6 on 2025-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_shipment_from_airport_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='from_airport_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_airport_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='from_airport_place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_airport_code',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_airport_name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='to_airport_place',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
