# Generated by Django 5.1.6 on 2025-02-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_shipment_from_airport_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
